### ISSUE TITLE
Compile error on parsing a string to java.time.LocalTime 

### ISSUE THREAD

**Issue by kazuki43zoo** [Macchinetta/server-guideline#2]
## Description

The following sample code is wrong. 

**Chapter:** アプリケーション形態に依存しない汎用機能
**Section:** 7.3. 日付操作(JSR-310 Date and Time API)
**Location:** [7.3.2.3.6. 文字列からのパース](https://macchinetta.github.io/server-guideline/1.5.1.RELEASE/ja/ArchitectureInDetail/GeneralFuncDetail/DateAndTime.html#id11)

```java
LocalTime localTime = LocalDate.parse("14:09:20", formatter2);
```
Type is mismatched.

## Possible Solutions

Should change `LocalDate.parse` to `LocalTime.parse`.

```java
LocalTime localTime = LocalTime.parse("14:09:20", formatter2);
```

## Affects Version/s
- All versions

## Fix Version/s
(To be written later by project member)

## Issue Links
* https://macchinetta.github.io/server-guideline/1.5.1.RELEASE/ja/ArchitectureInDetail/GeneralFuncDetail/DateAndTime.html#id11
* https://macchinetta.github.io/server-guideline-thymeleaf/current/ja/ArchitectureInDetail/GeneralFuncDetail/DateAndTime.html#id11

**Comment by macchinetta-fw** [comment]
@kazuki43zoo We'll fix it on next version. Thanks!

**Comment by kuriharaMa** [comment]
we fixed it.

**Comment by kazuki43zoo** [comment]
thx!
