### ISSUE TITLE
Improve the explanation about JCE Policy files on Encryption Chapter

### ISSUE THREAD

**Issue by kazuki43zoo** [Macchinetta/server-guideline#3]
## Description

I will propose to consider improving [the explanation about JCE Policy files](https://macchinetta.github.io/server-guideline/current/ja/Security/Encryption.html#how-to-use) because it includes since JDK/JRE 7u161 and 8u151. Further more, default policy change to `unlimited` from `limited` since JDK/JRE 7u171 and 8u161.

* https://bugs.java.com/view_bug.do?bug_id=8157561
* https://bugs.java.com/view_bug.do?bug_id=JDK-8170157

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
Nothing

**Comment by kuriharaMa** [comment]
@kazuki43zoo  Sorry for the late reply. We fixed it ,and thx.
[link about JCE files](https://macchinetta.github.io/server-guideline/1.6.1.RELEASE/ja/Security/Encryption.html#how-to-use)

**Comment by kazuki43zoo** [comment]
thx!
