### ISSUE TITLE
Datasources bean names are different between guideline's and blank projects'.

### ISSUE THREAD

**Issue by neriudon** [Macchinetta/server-guideline#4]
## Description
In section [6.1.2.3.1. log4jdbc提供のデータソースの設定](https://macchinetta.github.io/server-guideline/current/ja/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.html#log4jdbc), datasource's bean name is set `dataSourceSpied`.
On the other hand, in [multi blank project](https://github.com/Macchinetta/macchinetta-web-multi-blank/blob/ddc1e67c5c2408e0658467426d432506d2716d49/projectName-env/src/main/resources/META-INF/spring/projectName-env.xml#L12) and [single's](https://github.com/Macchinetta/macchinetta-web-blank/blob/7a7aadde1ae882c4cda97aa3a295d6dafedfd4c0/infra/common/META-INF/spring/projectName-env.xml#L12) -env.xml, datasource's bean name is set `realDataSource`.

If there is no particular reason, same names should be set.

## Possible Solutions
I think `realDataSource` is easier to understand than `dataSourceSpied`.

## Affects Version/s
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
- #XXX

**Comment by macchinetta-fw** [comment]
@neriudon 
Thank you for your suggestion. We'll improve our guideline in next version.

**Comment by kuriharaMa** [comment]
we fixed it.
